# Generated by Django 4.2.28 on 2026-04-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_asset_tag_asset_assigned_to_asset_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='asset_images/'),
        ),
    ]
