# Generated by Django 4.2.28 on 2026-04-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='last_checked',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='next_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
